[project]
name = "hs"
version = "0.1.0"
description = "Heart sound classification project for Ajou graduate ASR course"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch==2.5.1",
    "torchaudio==2.5.1",
    "torchvision==0.20.1",
    "numpy",
    "pandas",
    "scikit-learn",
    "pyyaml",
    "tqdm",
    "librosa",
    "soundfile",
    "scipy",
    "timm==0.4.5",
    "einops",
    "nnAudio",
    "jupyter",
    "ipykernel",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
